### ISSUE TITLE
Error when assigned asset is deleted

### ISSUE THREAD

**Issue by andyharris** [weareferal/craft-matrix-field-preview#36]
If you have a matrix preview block with an image asset assigned, and then you delete that asset via the assets screen, you get an error from any entries page that has that an instance of that block assigned to it.

`TypeError
Argument 1 passed to craft\services\Assets::getThumbUrl() must be an instance of craft\elements\Asset, null given, called in /xxx/public_html/vendor/weareferal/matrix-field-preview/src/records/PreviewRecord.php on line 64`

**Comment by timmyomahony** [comment]
Thanks @andyharris. So you're saying when you delete the image preview associated with the asset, but don't replace it with another, the entries page for that matrix field throw the error?

**Comment by andyharris** [comment]
Hi Timmy. That's correct, as long as that page has one of those blocks assigned (so you'd expect to see the mini preview), you get this error.

**Comment by timmyomahony** [comment]
Yeah, I'd have expected the default placeholder image to reappear. I'll check it out. Thanks for reporting.

**Comment by timmyomahony** [comment]
(Aiming to get a fix for this today or tomorrow)

**Comment by andyharris** [comment]
Awesome, thanks!

**Comment by timmyomahony** [comment]
@andyharris  are you running the latest version (`1.0.5`)? I can't replicate this. The assigned image gets deleted OK and I'm able to show the entries page and select a matrix block via the overlay without an error.

**Comment by timmyomahony** [comment]
Oh wait, I think I see what you  mean. So when you delete the image that you uploaded via the Matrix Field Preview settings page, but then deleted via the **Craft Assets panel** (not the Matrix Field Preview settings page) then you get the error. This would make sense, as the asset is deleted but the image in our custom table isn't.

**Comment by andyharris** [comment]
@timmyomahony Yep, the latter scenario is what I meant, sorry for not explaining it well.

**Comment by timmyomahony** [comment]
No worries. 

For my own notes:

This is happening because when you delete an asset file outside of the settings, the corresponding FK from our own `matrixpreviewfield_previewrecord` table to the assets isn't deleted. 

Usually this would be handled in the DB by the foreign key constraint on our table. Either "cascade" (where the whole row would be deleted when the corresponding asset is delete) or "null" where the FK column is set to null instead. 

The problem here is that it looks like Craft asset rows are _never_ deleted. Instead, the `keptFile` column on the `asset` file is just set up `False` when you delete the asset (and the underlying file is deleted).

In fact, Assets are just a child of Element, which all support "soft deletes":

https://docs.craftcms.com/v3/extend/soft-deletes.html#prepare-the-database-table

It looks like soft-deleted files will eventually get collected and fully deleted, but we can't wait for that. 

To handle this, we'll need to use an `EVENT_AFTER_DELETE` or something similar and listen for assets being deleted, then deleting our own files. This isn't ideal as it's potentially wasteful as we'll have to do a DB query every time an asset is deleted.

**Comment by timmyomahony** [comment]
I've added a fix for this in version 1.0.6. This is really just a quick-fix for the moment to stop the errors appearing. The full solution will require creating an event to listen for asset deletions to update our own tables but that's going to take a bit of time to get up and running
