### ISSUE TITLE
Matrix field not appearing when in a Supertable

### ISSUE THREAD

**Issue by hassanmah** [weareferal/craft-matrix-field-preview#62]
Hi,

I am using your plugin, but I've noticed when I have a Matrix block within a Supertable field within a Matrix block. The field doesn't show anything.

With Matrix Preview enabled (Accordion content missing):
<img width="972" alt="image" src="https://user-images.githubusercontent.com/3025707/113129489-dd039c00-9212-11eb-8c00-390c6798d73c.png">

With Matrix Preview disabled (Accordion content shows):
<img width="962" alt="image" src="https://user-images.githubusercontent.com/3025707/113129719-22c06480-9213-11eb-8d88-cb4a058b7edd.png">

With it enabled, I do get the following error in console:

`[Error] undefined
	(anonymous function) (BaseFieldPreview.js:40)
	(anonymous function)
	u (jquery.js:25:24456)
	fireWith (jquery.js:25:25200)
	S (jquery.js:25:76157)
	(anonymous function) (jquery.js:25:78615)`

Thanks

**Comment by timmyomahony** [comment]
Hi @hassanmah Currently, Neo and Spoon should be supported but we don't have Supertable support out-of-the-box. I actually haven't tried the plugin myself, so I will try it out and see if I can add support for nested matrix fields as described

**Comment by andyharris** [comment]
We've also run into this problem on another project, no way around it other than to disable the plugin entirely which is not ideal.

**Comment by timmyomahony** [comment]
Thanks @andyharris  I'll look at first adding some sort of check to make sure the plugin continues to work alongside SuperTable. I'd also like to look into actually supporting SuperTable

**Comment by daltonrooney** [comment]
I'm able to use the following structure:

Matrix -> SuperTable -> Matrix

The only thing was the nested Matrix button was missing because the "takeover" css was hiding it. I just submitted a pull request that makes the takeover CSS slightly more specific and the nested Matrix button is working now.

**Comment by timmyomahony** [comment]
I'm following up late here so apologies, but I'll be adding a fix from @daltonrooney to get this sorted so that this plugin doesn't interfere with any embedded matrix field previews within a Supertable.

As a matter of interest, is there any need to have previews for Supertable fields? Currently the plugin can add previews for Neo fields but I haven't added any integration for Supertable as I'm not familiar with the use cases. 

I imagine there could be potentially two uses:

- Add previews for Supertable fields themselves
- Add previews for any matrix fields used within a Supertable
