### ISSUE TITLE
Getting unknown property: weareferal\matrixfieldpreview\records\NeoBlockTypeConfigRecord::sortOrder

### ISSUE THREAD

**Issue by deanfields** [weareferal/craft-matrix-field-preview#86]
I'm playing around with a clean install, I have a Neo field that had one block, and I was able to add a preview. I have since added a second block and that has caused this error to occur on the Neo configure previews page. I removed one of the blocks and the page worked again.

**Comment by deanfields** [comment]
Having looked at the code and what is going on, the column 'sortOrder' is missing from the matrixfieldpreview_neo_blocktypes_config table for some reason, I didn't manually remove it, so not sure what happened.

**Comment by timmyomahony** [comment]
Thanks @deanfields. You're correct, the plugin has it's own tables in the DB to track previews. It should have added that field to the database via a migration though so not sure what's happened.

- You mentioned a clean install. Just to confirm, you were installing the plugin from scratch as well (as opposed to updating from an older version)?
- In which order did you install both Neo and the Matrix Field Preview plugin. MFP first then Neo or the other way?

**Comment by deanfields** [comment]
It was a fresh install of Craft 4 and I can't recall what order I installed the plugins in, but I feel like I may have installed MFP first. And yes, it was a fresh install as opposed to an update.

**Comment by timmyomahony** [comment]
This should now be fixed in release 4.0.3:

https://github.com/weareferal/craft-matrix-field-preview/releases/tag/4.0.3

The issue was that there was a migration I had failed to include in the code that runs when Neo is installed, meaning that `sortOrder` row wasn't installed properly. 

This should avoid the issue happening in the future but to fix an existing installation you might need to reinstall Neo so that the migration runs correctly. This would obviously mean losing configurations for Neo.

If that's too much hassle the easiest thing to do is to manually add a `sortOrder` column to the table `matrixfieldpreview_neo_blocktypes_config` in your database and make it type `smallint`

<img width="828" alt="CleanShot 2022-08-24 at 23 47 16@2x" src="https://user-images.githubusercontent.com/615149/186536898-1609b3e1-6317-4a1b-9505-6968ffb5f47b.png">
